[env]
TERM = "xterm-256color"

[scrolling]
history = 20000

[font]
normal = { family = "Fira Code" }
bold = { family = "Fira Code" }
italic = { family = "Fira Code" }
size = 16.0

[general]
import = ["~/.config/alacritty/dracula.toml"]

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[hints.enabled]
command = "open"
hyperlinks = true
post_processing = true
persist = false
binding = { key = "O", mods = "Control|Shift" }
